### ISSUE TITLE
json code to build the blog custom type

### ISSUE THREAD

**Issue by angelrod** [robindrost/prismic-eloquent-blog#1]
This is not a issue, would be great if you share the json code to build the blog's custom type for Prismic dashboard.

Great job!!

Thanks!

**Comment by robindrost** [comment]
`{
  "Main" : {
    "title" : {
      "type" : "StructuredText",
      "config" : {
        "single" : "heading1",
        "label" : "Title"
      }
    },
    "hero_image" : {
      "type" : "Image",
      "config" : {
        "constraint" : { },
        "thumbnails" : [ {
          "name" : "hero",
          "width" : 1200,
          "height" : 370
        }, {
          "name" : "teaser",
          "width" : 480,
          "height" : 290
        } ],
        "label" : "Hero image"
      }
    },
    "teaser" : {
      "type" : "StructuredText",
      "config" : {
        "multi" : "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
        "label" : "Teaser"
      }
    },
    "body" : {
      "type" : "StructuredText",
      "config" : {
        "multi" : "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
        "label" : "Body"
      }
    },
    "related_blog_posts" : {
      "type" : "Group",
      "config" : {
        "fields" : {
          "blog_post" : {
            "type" : "Link",
            "config" : {
              "select" : "document",
              "customtypes" : [ "blog_post" ],
              "label" : "blog post"
            }
          }
        },
        "label" : "Related blog posts"
      }
    }
  },
  "Meta data" : {
    "uid" : {
      "type" : "UID",
      "config" : {
        "label" : "Slug"
      }
    }
  }
}`
